name: ai_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.0.15
  intl: ^0.20.2
  animate_do: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/splash.png"  # Path to your image

# The "flutter_lints" package below contains a set of recommended lints to
# encourage good coding practices. The lint set provided by the package is
# activated in the `analysis_options.yaml` file located at the root of your
# package. See that file for information about deactivating specific lint
# rules and activating additional ones.
flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/splash.png
    - assets/menu1.jpg
    - assets/menu2.jpg
    - assets/menu3.jpg
    - assets/special.jpg
    - assets/offer1.jpg
    - assets/offer2.jpg
    - assets/offer3.jpg
    - assets/offer4.jpg
    - assets/offer5.png
    - assets/offer6.jpg
    - assets/login.png
    - assets/zinger.jpg
    - assets/loadedcheese.jpg
    - assets/tandoori.jpg
    - assets/nashville.jpg
  uses-material-design: true


